---

- name: Create/Update Users
  when: primary_controller|bool
  template:
    src:   etc/cron.d/slurm_users_groups
    dest: /etc/cron.d/slurm_users_groups
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Test create_users_groups.py
  shell: |
    set -ex

    {{ slurm_config_dir }}/bin//create_users_groups.py -i {{ slurm_config_dir }}/users_groups.json
