---

- name: Install python3
  yum:
    state: present
    name:
      - python3
      - python3-pip

- name: Install pyyaml
  pip:
    executable: /usr/bin/pip3
    state: present
    name:
      - pyyaml

- name: Create {{ slurm_config_dir }}/bin/create_slurm_accounts.py
  when: primary_controller|bool
  copy:
    dest: "{{ slurm_config_dir }}/bin/create_slurm_accounts.py"
    src:  opt/slurm/config/bin/create_slurm_accounts.py
    owner: root
    group: root
    mode: 0755

- name: Create {{ slurm_config_dir }}/accounts.yml
  when: primary_controller|bool
  copy:
    dest: "{{ slurm_config_dir }}/accounts.yml"
    src:  opt/slurm/config/accounts.yml.example
    owner: root
    group: root
    mode: 0664
    backup: yes
    force: false # Don't overwrite changes

# create_slurm_accounts.py writes a logfile to /var/logs/slurm
- name: Create /var/log/slurm
  when: primary_controller|bool
  file:
    path: "/var/log/slurm"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Run {{ slurm_config_dir }}/bin/create_slurm_accounts.py to make sure it works
  # This uses sacctmcr so must do this after slurmctld and slurmdbd are working.
  when: primary_controller|bool and accounting_storage_host and licenses
  shell:
    cmd: |
      set -ex

      export SLURM_ROOT={{ slurm_root }}
      {{ slurm_config_dir }}/bin/create_slurm_accounts.py --accounts {{ slurm_config_dir }}/accounts.yml --users {{ slurm_config_dir }}/users_groups.json --default-account unassigned -d

- name: Create /etc/cron.d/slurm_accounts
  when: primary_controller|bool
  template:
    src:   etc/cron.d/slurm_accounts
    dest: /etc/cron.d/slurm_accounts
    owner: root
    group: root
    mode: 0600
    force: yes
