---

- name: Show vars used in this playbook
  debug:
    msg: |
      Architecture:               {{Architecture}}
      ClusterName:                {{ClusterName}}
      DefaultPartition:           {{DefaultPartition}}
      distribution:               {{distribution}}
      distribution_major_version: {{distribution_major_version}}
      ModulefilesBaseDir:         {{ModulefilesBaseDir}}
      ParallelClusterVersion:     {{ParallelClusterVersion}}
      SlurmBaseDir:               {{SlurmBaseDir}}
      SlurmConfigDir:             {{SlurmConfigDir}}
      SlurmVersion:               {{SlurmVersion}}

- name: Fix permissions on config dir so users can access it.
  file:
    path: "{{SlurmConfigDir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create {{ModulefilesBaseDir}}/{{distribution}}/{{distribution_major_version}}/{{Architecture}}/{{ClusterName}}
  file:
    path: "{{ModulefilesBaseDir}}/{{distribution}}/{{distribution_major_version}}/{{Architecture}}/{{ClusterName}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create slurm modulefile .template
  template:
    dest: "{{ModulefilesBaseDir}}/{{distribution}}/{{distribution_major_version}}/{{Architecture}}/{{ClusterName}}/.template"
    src:  opt/slurm/modules/modulefiles/slurm/.template
    owner: root
    group: root
    mode: 0664
    force: yes

- name: Create slurm modulefile
  file:
    path: "{{ModulefilesBaseDir}}/{{distribution}}/{{distribution_major_version}}/{{Architecture}}/{{ClusterName}}/{{ParallelClusterVersion}}"
    src:  "{{ModulefilesBaseDir}}/{{distribution}}/{{distribution_major_version}}/{{Architecture}}/{{ClusterName}}/.template"
    state: link
    owner: root
    group: root
    mode: 0664

- name: Create slurm modulefile .version
  template:
    dest: "{{ModulefilesBaseDir}}/{{distribution}}/{{distribution_major_version}}/{{Architecture}}/{{ClusterName}}/.version"
    src:   opt/slurm/modules/modulefiles/slurm/.version
    owner: root
    group: root
    mode: 0664
    force: yes
