---

- name: Install libjwt-devel on non-Amazon arm64
  when: not(distribution == 'Amazon' and architecture == 'arm64')
  yum:
    state: present
    name:
      - libjwt-devel

- name: Install libjwt-devel on Amazon arm64
  when: distribution == 'Amazon' and architecture == 'arm64'
  shell: |
    set -xe

    cd /tmp
    rm -rf libjwt
    git clone --depth 1 --single-branch -b v1.12.0 https://github.com/benmcollins/libjwt.git libjwt
    cd libjwt
    autoreconf --force --install
    ./configure --prefix=/usr/local
    make -j
    make install

- name: Build {{ slurm_sbin_dir }}/slurmrestd
  when: primary_controller|bool
  args:
    creates: "{{ slurm_sbin_dir }}/slurmrestd"
  shell:
    cmd: |
      set -ex

      source /opt/parallelcluster/pyenv/versions/{{ parallel_cluster_python_version }}/envs/cookbook_virtualenv/bin/activate

      cd /etc/chef/local-mode-cache/cache/slurm-slurm-{{ pc_slurm_version }}
      ./configure --prefix /opt/slurm --with-pmix=/opt/pmix --with-slurmrestd --enable-slurmrestd &> configure.log
      CORES=$(grep processor /proc/cpuinfo | wc -l)
      make -j $CORES         &> make_all.log
      make -j $CORES contrib &> make_contrib.log
      make install           &> make_install.log
      make install-contrib   &> make_install-contrib.log

- name: Create slurmrestd user
  user:
    name: slurmrestd
    system: yes
    uid: '{{ slurmrestd_uid }}'
    create_home: no

- name: Create {{ slurmrestd_socket_dir }}
  when: primary_controller|bool
  file:
    path: "{{ slurmrestd_socket_dir }}"
    state: directory
    owner: slurmrestd
    group: slurmrestd
    mode: 0755

- name: Create {{ slurm_spool_dir }}
  when: primary_controller|bool
  file:
    path: "{{ slurm_spool_dir }}"
    state: directory
    owner: slurmrestd
    group: slurmrestd
    mode: 0755

- name: Create jwt key for slurmrestd
  when: primary_controller|bool
  args:
    creates: "{{ slurm_spool_dir }}/jwt_hs256.key"
  shell:
    cmd: |
      set -ex

      dd if=/dev/random of={{ slurm_spool_dir }}/jwt_hs256.key bs=32 count=1
      chown slurm:slurm {{ slurm_spool_dir }}/jwt_hs256.key
      chmod 0600 {{ slurm_spool_dir }}/jwt_hs256.key

- name: Create /etc/sysconfig/slurmrestd
  template:
    dest: /etc/sysconfig/slurmrestd
    src:   etc/sysconfig/slurmrestd
    owner: root
    group: root
    mode: 0644
    force: yes
  register: sysconfig_slurmrestd_result

- name: Create /opt/slurm/config/bin/update_slurmrestd_jwt_parameter.sh
  when: primary_controller|bool
  template:
    dest: /opt/slurm/config/bin/update_slurmrestd_jwt_parameter.sh
    src:   opt/slurm/config/bin/update_slurmrestd_jwt_parameter.sh
    owner: root
    group: root
    mode: 0755

- name: Cron to update slurmrestd JWT for root
  when: primary_controller|bool
  template:
    src:   etc/cron.d/update_slurmrestd_jwt_for_root
    dest: /etc/cron.d/update_slurmrestd_jwt_for_root
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Cron to update slurmrestd JWT for slurmrestd
  when: primary_controller|bool
  template:
    src:   etc/cron.d/update_slurmrestd_jwt_for_slurmrestd
    dest: /etc/cron.d/update_slurmrestd_jwt_for_slurmrestd
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Update /etc/systemd/system/slurmrestd.service
  template:
    dest: /etc/systemd/system/slurmrestd.service
    src:   etc/systemd/system/slurmrestd.service
    owner: root
    group: root
    mode: 0644
  register: slurmrestd_service_result

- name: Get service facts
  service_facts:

- name: Restart slurmrestd
  when: ansible_facts.services['slurmrestd.service']['state'] == 'running' and (sysconfig_slurmrestd_result.changed or slurmrestd_service_result.changed)
  systemd:
    name: slurmrestd
    enabled: yes
    daemon_reload: yes
    state: restarted
  register: slurmrestd_restarted

- name: Start slurmrestd
  service:
    name: slurmrestd
    enabled: yes
    state: started
  register: slurmrestd_started

- name: Wait for {{ slurm_bin_dir }}/scontrol
  wait_for:
    path: "{{ slurm_bin_dir }}/scontrol"
    timeout: 1800 # 30 minutes

- name: Wait for slurmctld to accept requests on port {{ slurmctld_port_min }}
  wait_for:
    host: "127.0.0.1"
    port: "{{ slurmctld_port_min }}"
    timeout: 1800 # 30 minutes

- name: Test scontrol token
  when: primary_controller|bool
  shell: |
    set -xe

    {{ slurm_bin_dir }}/scontrol token
