---
# Tasks for ParallelClusterCreateUsersGroupsJsonConfigure

- name: Show vars used in this playbook
  debug:
    msg: |
      ClusterName:                {{ClusterName}}
      Region:                     {{Region}}
      SlurmConfigDir:             {{SlurmConfigDir}}

- name: Add /opt/slurm/{{ClusterName}} to /etc/fstab
  mount:
    path: /opt/slurm/{{ClusterName}}
    src:  "head_node.{{ClusterName}}.pcluster:/opt/slurm"
    fstype: nfs
    backup: true
    state: present # Should already be mounted

- name: Create {{SlurmConfigDir}}/users_groups.json
  shell: |
    set -ex

    {{SlurmConfigDir}}/bin/create_or_update_users_groups_json.sh

- name: Create cron to refresh {{SlurmConfigDir}}/users_groups.json every hour
  template:
    dest: /etc/cron.d/slurm_{{ClusterName}}_update_users_groups_json
    src:   etc/cron.d/slurm_update_users_groups_json
    owner: root
    group: root
    mode: 0600
    force: yes
