---
# Tasks for ParallelClusterCreateUsersGroupsJsonConfigure

- name: Show vars used in this playbook
  debug:
    msg: |
      cluster_name:               {{ cluster_name }}
      region:                     {{ region }}
      slurm_config_dir:           {{ slurm_config_dir }}

- name: Add /opt/slurm/{{ cluster_name }} to /etc/fstab
  mount:
    path: /opt/slurm/{{ cluster_name }}
    src:  "head_node.{{ cluster_name }}.pcluster:/opt/slurm"
    fstype: nfs
    backup: true
    state: present # Should already be mounted

- name: Create {{ slurm_config_dir }}/users_groups.json
  shell: |
    set -ex

    {{ slurm_config_dir }}/bin/create_or_update_users_groups_json.sh
  args:
    creates: '{{ slurm_config_dir }}/users_groups.json'

- name: Create cron to refresh {{ slurm_config_dir }}/users_groups.json every hour
  template:
    dest: /etc/cron.d/slurm_{{ cluster_name }}_update_users_groups_json
    src:   etc/cron.d/slurm_update_users_groups_json
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Create /opt/aws-eda-slurm-cluster/{{ cluster_name }}
  file:
    path: /opt/aws-eda-slurm-cluster/{{ cluster_name }}
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Create /opt/aws-eda-slurm-cluster/{{ cluster_name }}/bin
  file:
    path: /opt/aws-eda-slurm-cluster/{{ cluster_name }}/bin
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Copy {{ slurm_config_dir }}/bin/create_users_groups_json_deconfigure.sh to /opt/aws-eda-slurm-cluster/{{ cluster_name }}/bin/
  copy:
    src: "{{ slurm_config_dir }}/bin/create_users_groups_json_deconfigure.sh"
    dest: /opt/aws-eda-slurm-cluster/{{ cluster_name }}/bin/create_users_groups_json_deconfigure.sh
    remote_src: true
    force: true   # Has to be true or won't be copied when they are different.
    owner: root
    group: root
    mode: 0700

- name: Copy {{ slurm_config_dir }}/ansible/ to /opt/aws-eda-slurm-cluster/{{ cluster_name }}/ansible/
  copy:
    src: "{{ slurm_config_dir }}/ansible"
    dest: /opt/aws-eda-slurm-cluster/{{ cluster_name }}/
    remote_src: true
    force: true   # Has to be true or won't be copied when they are different.
    owner: root
    group: root
    directory_mode: 0700
    mode: 0600
