---
- name: Configure ParallelCluster Head Node
  hosts: ParallelClusterHeadNode
  become_user: root
  become: yes
  roles:
    - all
    - ParallelClusterHeadNode
    - security_updates
    - bug_fixes
