---
- name: Configure ParallelCluster Head Node
  hosts: ParallelClusterHeadNode
  become_user: root
  become: yes
  roles:
    - all
    - ParallelClusterHeadNode
    - role: exostellar_infrastructure_optimizer
      when: xio_mgt_ip is defined
    - security_updates
    - bug_fixes
