site_name: EDA SLURM Cluster on AWS
repo_url: https://github.com/aws-samples/aws-eda-slurm-cluster
docs_dir: docs
nav:
  - 'index.md'
  - 'deploy.md'
  - 'run_jobs.md'
  - 'job_preemption.md'
  - 'rest_api.md'
  - 'onprem.md'
  - 'soca_integration.md'
  - 'f1-ami.md'
  - 'federation.md'
  - 'multi-region.md'
  - 'plugin-integration.md'
  - 'implementation.md'
  - 'debug.md'
strict: true
theme:
  name: mkdocs
  #name: readthedocs
  hljs_languages:
    - python
    - yaml
  navigation_depth: 4
  nav_style: dark
  features:
    - navigation.tabs
