site_name: EDA SLURM Cluster on AWS
repo_url: https://github.com/aws-samples/aws-eda-slurm-cluster
docs_dir: docs
nav:
  - 'index.md'
  - 'deployment-prerequisites.md'
  - 'security-groups.md'
  - 'deploy-parallel-cluster.md'
  - 'config.md'
  - 'res_integration.md'
  - 'soca_integration.md'
  - 'exostellar-infrastructure-optimizer.md'
  - 'custom-amis.md'
  - 'run_jobs.md'
  - 'job_preemption.md'
  - 'rest_api.md'
  - 'onprem.md'
  - 'containers.md'
 # - 'federation.md'
  - 'delete-cluster.md'
 # - 'implementation.md'
  - 'debug.md'
strict: true
theme:
  name: mkdocs
  #name: readthedocs
  hljs_languages:
    - python
    - yaml
  navigation_depth: 4
  nav_style: dark
  features:
    - navigation.tabs
