---
- name: Install munge
  yum:
    state: present
    name:
      - munge

- name: Copy {{SlurmConfigDir}}/munge.key to /etc/munge/munge.key
  copy:
    dest: /etc/munge/munge.key
    remote_src: true
    src: "{{SlurmConfigDir}}/munge.key"
    owner: munge
    group: munge
    mode: 0400

- name: Create /var/run/munge
  file:
    path: /var/run/munge
    state: directory
    owner: munge
    group: munge
    mode: 0755

- name: Start munge
  service:
    name: munge
    enabled: yes
    state: restarted
