# Template build file

Image:
  Name: {{ImageName}}
  RootVolume:
    Size: {{RootVolumeSize}}

Build:
  InstanceType: {{InstanceType}}
  SubnetId: {{SubnetId}}
  SecurityGroupIds:
    - {{ImageBuilderSecurityGroupId}}
  ParentImage: {{ParentImage}}
  UpdateOsPackages:
    Enabled: false
{%- if ComponentS3Url %}
  Components:
    - Type: script
      Value: {{ComponentS3Url}}
{%- endif %}
  Iam:
    AdditionalIamPolicies:
      - Policy: {{AssetReadPolicyArn}}

DevSettings:
  TerminateInstanceOnFailure: false
