---

# See https://slurm.schedmd.com/big_sys.html

- name: Set eth0 txqueuelen to 4096
  shell: ifconfig eth0 txqueuelen 4096

# This is set to 392,837 by default on Amazon Linux 2
# - name: Configure kernel parameter fs.file-max
#   sysctl:
#     name: fs.file-max
#     value: "392837"
#     sysctl_file: /etc/sysctl.d/slurmctl.conf

- name: Configure kernel parameter net.ipv4.tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: "4096"
    sysctl_file: /etc/sysctl.d/slurmctl.conf

- name: Configure kernel parameter net.ipv4.tcp_syncookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: "1"
    sysctl_file: /etc/sysctl.d/slurmctl.conf

- name: Configure kernel parameter net.core.somaxconn
  sysctl:
    name: net.core.somaxconn
    value: "4096"
    sysctl_file: /etc/sysctl.d/slurmctl.conf
