---

- name: Install epel from amazon-linux-extras
  when: ansible_facts['distribution'] == 'Amazon'
  shell:
    cmd: amazon-linux-extras install -y epel
    creates: /etc/yum.repos.d/epel.repo

- name: Install epel
  when: ansible_facts['distribution'] == 'CentOS'
  yum:
    state: present
    disablerepo: "{{yum_disablerepo|default(omit)}}"
    name:
      - epel-release

- name: Install Slurm controller packages
  yum:
    state: present
    disablerepo: "{{yum_disablerepo|default(omit)}}"
    name:
      - crudini
      - emacs
      - environment-modules
      - figlet
      - gcc
      - http-parser-devel
      - jq
      - json-c-devel
      - mailx
      - munge
      - munge-libs
      - munge-devel
      - ncurses-compat-libs
      - python3
      - rng-tools

- name: Install libjwt on non-Amazon arm64
  when: not(distribution == 'Amazon' and Architecture == 'arm64')
  yum:
    state: present
    name:
      - libjwt

- name: Install packages to build libjwt
  when: distribution == 'Amazon' and Architecture == 'arm64'
  yum:
    state: present
    disablerepo: "{{yum_disablerepo|default(omit)}}"
    name:
      - autoconf
      - automake
      - git
      - jansson-devel
      - libtool
      - openssl-devel

- name: Install libjwt on Amazon arm64
  when: distribution == 'Amazon' and Architecture == 'arm64'
  shell: |
    set -xe

    cd /tmp
    rm -rf libjwt
    git clone --depth 1 --single-branch -b v1.12.0 https://github.com/benmcollins/libjwt.git libjwt
    cd libjwt
    autoreconf --force --install
    ./configure --prefix=/usr/local
    make -j
    make install

- name: Install pip3 packages
  pip:
    executable: /usr/bin/pip3
    state: present
    name:
      - boto3
      - isodate
      - jinja2
      - python-hostlist

- name: Install latest awscli
  pip:
    executable: /usr/bin/pip3
    state: latest
    name:
      - awscli

- name: Create /etc/rc.d/rc.local
  template:
    src:   etc/rc.d/rc.local
    dest: /etc/rc.d/rc.local
    owner: root
    group: root
    mode: 0700
    force: yes
