---

- name: Create {{SlurmScriptsDir}}/update_slurmrestd_jwt_parameter.sh
  when: PrimaryController|bool
  template:
    dest: "{{SlurmScriptsDir}}/update_slurmrestd_jwt_parameter.sh"
    src:   opt/slurm/cluster/bin/update_slurmrestd_jwt_parameter.sh
    owner: root
    group: root
    mode: 0755

- name: Cron to update slurmrestd JWT for root
  when: PrimaryController|bool
  template:
    src:   etc/cron.d/update_slurmrestd_jwt_for_root
    dest: /etc/cron.d/update_slurmrestd_jwt_for_root
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Cron to update slurmrestd JWT for slurmrestd
  when: PrimaryController|bool
  template:
    src:   etc/cron.d/update_slurmrestd_jwt_for_slurmrestd
    dest: /etc/cron.d/update_slurmrestd_jwt_for_slurmrestd
    owner: root
    group: root
    mode: 0600
    force: yes
