---

- name: Create slurm user
  user:
    name: slurm
    system: yes
    uid: '{{SlurmUid}}'
    create_home: no

- name: Create slurmrestd user
  user:
    name: slurmrestd
    system: yes
    uid: '{{SlurmrestdUid}}'
    create_home: no
