---
#====================================================================
# Sample configuraton that creates a minimal Slurm cluster
#
# NOTE: This is just an example.
#     Please create your own revision controlled config file.
#
# No SlurmDbd in this configuration.
# Configure 5 each of t3 instance types.
#
# This config doesn't provide required parameters like VpcId so you must
# use the --prompt option with it.
# To use:
#     source setup.sh
#     ./install.sh --config-file source/config/default_config.yml --prompt
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmminimal-config

# @TODO: Add Region
# Region: {{Region}}

# @TODO: Add your SshKeyPair
# SshKeyPair: {{SshKeyPair}}

# @TODO: Update with your VPC
# VpcId: vpc-xxxxxxxxxxxxxxxxx

# @TODO: Update with your private subnet in your VPC
# SubnetId: subnet-xxxxxxxxxxxxxxxxx

# @TODO: Update with your SNS Topic. Make sure to subscribe your email address to the topic and confirm the subscription
# ErrorSnsTopicArn: arn:aws:sns:{{Region}}:{{AccountId}}:{{TopicName}}

# @TODO: Add your preferred timezone so times aren't in UTC
# TimeZone: America/Chicago # America/Los_Angeles or America/Denver or America/New_York

# @TODO: If using Research and Engineering Studio, update with environment name
# RESEnvironmentName: {{ResEnvironmentName}}

slurm:
  ParallelClusterConfig:
    Version: 3.12.0
    # @TODO: Choose the CPU architecture: x86_64, arm64. Default: x86_64
    # Architecture: x86_64
    # @TODO: Update DatabaseStackName with stack name you deployed ParallelCluster database into. See: https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_07_slurm-accounting-v3.html#slurm-accounting-db-stack-v3
    # Database:
    #   DatabaseStackName: {{DatabaseStackName}}

  MungeKeySecret: SlurmMungeKey

  SlurmCtl: {}

  InstanceConfig:
    UseSpot: true
    Include:
      # @TODO: Update InstanceFamiles and InstanceTypes to use in your cluster
      InstanceFamilies:
        - t3
      InstanceTypes: []
    NodeCounts:
      # @TODO: Update the max number of each instance type to configure
      DefaultMaxCount: 5
      # @TODO: You can update the max instance count for each compute resource
      # ComputeResourceCounts:
      #   od-1024gb-16-cores: # x2iedn.8xlarge', x2iezn.8xlarge
      #     MaxCount: 1
      #   sp-1024gb-16-cores: # x2iedn.8xlarge', x2iezn.8xlarge
      #     MaxCount: 2

  # @TODO: Configure storage mounts
  # storage:
  #   ExtraMounts:
  #     - dest: /home
  #       StorageType: Efs
  #       FileSystemId: 'fs-xxxxxxxxxxxxxxxxx'
  #       src: fs-xxxxxxxxxxxxxxxxx.efs.{{Region}}.amazonaws.com:/
  #       type: nfs4
  #       options: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
  #   ExtraMountSecurityGroups:
  #     nfs:
  #       DCV-Host: sg-xxxxxxxxxxxxxxxxx

# @TODO: Configure license counts
Licenses:
  vcs:
    Count: 10
    Server: synopsys_licenses
    Port: '24680'
    ServerType: flexlm
