---
#====================================================================
# Sample configuraton that creates a minimal Slurm cluster
#
# No SlurmDbd in this configuration.
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmminimal

slurm:
  ParallelClusterConfig:
    Enable: true

  SlurmCtl: {}

  # InstanceConfig:
  # Configure the instances used by the cluster
  # A partition will be created for each combination of Base OS, Architecture, and Spot
  InstanceConfig:
    UseSpot: true
    BaseOsArchitecture:
      RedHat:
        8: [x86_64]
    Include:
      InstanceFamilies:
        - t3
      InstanceTypes: []
    NodeCounts:
      DefaultMaxCount: 5
