---
#====================================================================
# Minimal Slurm cluster with an ElasticSearch domain
#
# Creates a new domain and configures Slurm to write completed job information to the domain.
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmes

slurm:
  # ElasticSearch:
  # data_nodes: Must be a multiple of number_of_azs
  ElasticSearch:
    ebs_volume_size: 20
    ebs_volume_type: GP2
    enable_version_upgrade: False
    number_of_azs: 2
    master_nodes: 3
    master_node_instance_type: m5.large.search
    data_nodes: 2
    data_node_instance_type: m5.large.search
    warm_nodes: 0
    warm_instance_type: ultrawarm.medium.search

  # JobCompType:
  # Values:
  #     jobcomp/none
  #     jobcomp/elasticsearch
  #     jobcomp/filetxt
  JobCompType: jobcomp/elasticsearch

  InstanceConfig:
    UseSpot: true
    DefaultPartition: CentOS_7_x86_64_spot
    NodesPerInstanceType: 10
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
      CentOS:
        7: [x86_64]
    Include:
      MaxSizeOnly: false
      InstanceFamilies:
        - t3
        - t4g
      InstanceTypes: []
    Exclude:
      InstanceFamilies: []
      InstanceTypes:
        - '.+\.(micro|nano)'   # Not enough memory
        - '.*\.metal'

  # Use defaults from schema
  SlurmCtl: {}
  storage: {'zfs': {}}
