---
#====================================================================
# Test Rocky linux support
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmrocky

slurm:
  InstanceConfig:
    UseSpot: true
    DefaultPartition: Rocky_8_x86_64_spot
    NodesPerInstanceType: 5
    BaseOsArchitecture:
      Rocky: {8: [x86_64, arm64]}
    Include:
      MaxSizeOnly: false
      InstanceFamilies:
        - t3
        - t4g
      InstanceTypes: []
    Exclude:
      InstanceFamilies: []
      InstanceTypes:
        - '.*\.metal'

  # Use defaults from schema
  SlurmCtl: {}
  storage: {'zfs': {}}
