---
#====================================================================
# Federated Slurm cluster for EDA
#
# This is the first AZ that other AZs will reference.
# Other federated clusters will share this cluster's SlurmDbd instance.
# Redundant controllers and typical instances used by EDA.
# Uses CentOS 7 and AlmaLinux 8 and both x86_64 and arm64 architectures.
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmedaaz1

# Add your subnet id
SubnetId: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet1

# This is optional, but highly recommended
#ErrorSnsTopicArn: arn:aws:sns:{{region}}:{AccountId}:{TopicName}

slurm:
  SlurmCtl:
    # For high availability configure multiple controllers
    NumberOfControllers: 2

  # The accounting database is required to enable fairshare scheduling
  # It is managed by the Slurm Database Daemon (slurmdbd) instance
  SlurmDbd: {}

  Federation:
    Name: slurmeda
    FederatedClusterStackNames: []

  # Configure typical EDA instance types
  # A partition will be created for each combination of Base OS, Architecture, and Spot
  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 5
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
      CentOS:
        7: [x86_64]

  # Use defaults from schema
  storage: {'zfs': {}}
