---
#====================================================================
# Slurm cluster that uses FSx for NetApp ONTAP for storing the Slurm configuration and tool files
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmontap
slurm:
  storage:
    provider: ontap
    ontap: {} # This causes the defaults from the schema to be applied.

  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 10
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
      CentOS:
        7: [x86_64]
    Include:
      InstanceFamilies:
        - t3
        - t4g
      InstanceTypes: []

  # Use defaults from schema
  SlurmCtl: {}
