---
#====================================================================
# Slurm cluster to test Alma Linux support
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================


StackName: slurmalma

slurm:
  # InstanceConfig:
  # Configure the instances used by the cluster
  # A partition will be created for each combination of Base OS, Architecture, and Spot
  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 10
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
    Include:
      InstanceFamilies:
        - t3
        - t4g
      InstanceTypes: []

  # Use defaults from schema
  SlurmCtl: {}
  storage: {'zfs': {}}
