---
#====================================================================
# Slurm cluster that uses the AWS FPGA Developer AMI as the base AMI for compute nodes.
#
# Based on the EDA configuration.
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmedafpga

slurm:
  SlurmNodeAmis:
    # AWS FPGA Developer AMIs
    BaseAmis:
      us-east-1:
        Amazon: {2: {x86_64: {ImageId: ami-0efdec76678df9a64, RootDeviceSize: '+5'}}}
        CentOS: {7: {x86_64: {ImageId: ami-02155c6289e76719a, RootDeviceSize: '+5'}}}

  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 5
    BaseOsArchitecture:
      Amazon:
        2: [x86_64]
      CentOS:
        7: [x86_64]
    Include:
      InstanceFamilies:
        - 'c6a'               # AMD EPYC 7R13 Processor           3.6 GHz
        - 'c6i'               # Intel Xeon 8375C (Ice Lake)       3.5 GHz
        - 'f1'                # Intel Xeon E5-2686 v4 (Broadwell) 2.3 GHz
        - 'm5zn'              # Intel Xeon Platinum 8252          4.5 GHz
        - 'm6a'               # AMD EPYC 7R13 Processor           3.6 GHz
        - 'm6i'               # Intel Xeon 8375C (Ice Lake)       3.5 GHz
        - 'r6i'               # Intel Xeon 8375C (Ice Lake)       3.5 GHz 1TB
        - 'x2idn'             # Intel Xeon Scalable (Icelake)     3.5 GHz 2 TB
        - 'x2iedn'            # Intel Xeon Scalable (Icelake)     3.5 GHz 4 TB
        - 'x2iezn'            # Intel Xeon Platinum 8252          4.5 GHz 1.5 TB
        - 'z1d'               # Intel Xeon Platinum 8151          4.0 GHz
      InstanceTypes: []

  # Use defaults from schema
  SlurmCtl: {}
  storage: {'zfs': {}}
