---
#====================================================================
# Slurm cluster for EDA
#
# Redundant controllers and typical instances used by EDA.
# Uses CentOS 7 and AlmaLinux 8 and both x86_64 and arm64 architectures.
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmeda

slurm:
  SlurmCtl:
    # For high availability configure multiple controllers
    NumberOfControllers: 2

  # The accounting database is required to enable fairshare scheduling
  # It is managed by the Slurm Database Daemon (slurmdbd) instance
  SlurmDbd: {}

  # Configure typical EDA instance types
  # A partition will be created for each combination of Base OS, Architecture, and Spot
  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 5
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
      CentOS:
        7: [x86_64]

  # Use defaults from schema
  storage: {'zfs': {}}
