---
#====================================================================
# Slurm cluster that uses FSx for OpenZfs for storing the Slurm configuration and tool files
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmzfs

slurm:
  storage:
    provider: zfs
    zfs: {} # This causes the defaults from the schema to be applied.

  InstanceConfig:
    UseSpot: true
    DefaultPartition: AlmaLinux_8_arm64_spot
    NodesPerInstanceType: 10
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
      CentOS:
        7: [x86_64]
    Include:
      MaxSizeOnly: false
      InstanceFamilies:
        - t3
        - t4g
      InstanceTypes: []
    Exclude:
      InstanceFamilies: []
      InstanceTypes:
        - '.+\.(micro|nano)'   # Not enough memory
        - '.*\.metal'

  # Use defaults from schema
  SlurmCtl: {}
