---
#====================================================================
# Federated Slurm cluster for EDA
#
# This is the 3rd AZ that must be created after the 1st AZ and 2nd clusters.
# Shares the SlurmDbd instance from the 1st AZ's cluster.
# Redundant controllers and typical instances used by EDA.
# Uses CentOS 7 and AlmaLinux 8 and both x86_64 and arm64 architectures.
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmedaaz3

# Add your subnet id
SubnetId: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet3

# This is optional, but highly recommended
#ErrorSnsTopicArn: arn:aws:sns:{{region}}:{AccountId}:{TopicName}

slurm:
  SlurmCtl:
    # For high availability configure multiple controllers
    NumberOfControllers: 2

  # Re-use the SlurmDbd instance from slurmedaaz1
  ExistingSlurmDbd:
    StackName: slurmedaaz1

  Federation:
    Name: slurmeda
    FederatedClusterStackNames:
      - slurmedaaz1
      - slurmedaaz2

  # Configure typical EDA instance types
  # A partition will be created for each combination of Base OS, Architecture, and Spot
  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 5
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
      CentOS:
        7: [x86_64]

  # Use defaults from schema
  storage: {'zfs': {}}
