---
# Multi-region Slurm cluster with Netapp Ontap

StackName: slurmmultiaz

#Region: us-east-1

#SshKeyPair: name of your ec2 keypair

#VpcId: vpc-xxxxxxxxxxxxxxxxx

#SubnetId: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet1

#HostedZoneId: XXXXXXXXXXXXXXXXXXX

# This is optional, but highly recommended
#ErrorSnsTopicArn: arn:aws:sns:{{region}}:{AccountId}:{TopicName}

#TimeZone: 'US/Central'

slurm:
  MungeKeySsmParameter: "/slurm/munge_key"

  SlurmCtl:
    NumberOfControllers: 2

  SlurmDbd: {}

  # External security groups that should be able to use the cluster
  # SubmitterSecurityGroupIds:
  #   soca-ComputeNodeSG: sg-xxxxxxxxxxxxxxxxx

  # SubmitterInstanceTags:
  #   'soca:ClusterId': ['soca-xyz']

  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 10
    BaseOsArchitecture:
      AlmaLinux: {8: [x86_64, arm64]}
      CentOS:
        7: [x86_64]
    Include:
      InstanceFamilies:
        - t3
        - t4g
      InstanceTypes: []
    Regions:
      eu-west-1:
        VpcId: vpc-xxxxxxxxxxxxxxxxx
        CIDR: 10.1.0.0/16
        SshKeyPair: admin-eu-west-1
        AZs:
          - Priority: 10
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet1
          - Priority: 9
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet2
          - Priority: 8
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet3
      us-east-1:
        VpcId: vpc-xxxxxxxxxxxxxxxxx
        CIDR: 10.2.0.0/16
        SshKeyPair: admin-us-east-1
        AZs:
          - Priority: 7
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet1
          - Priority: 6
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet2
          - Priority: 5
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet3
      us-west-2:
        VpcId: vpc-xxxxxxxxxxxxxxxxx
        CIDR: 10.3.0.0/16
        SshKeyPair: admin-us-west-2
        #SecurityGroupId: sg-0addccc8388e008fd
        AZs:
          - Priority: 4
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet1
          - Priority: 3
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet2
          - Priority: 2
            Subnet: subnet-xxxxxxxxxxxxxxxxx # PrivateSubnet3

  storage:
    provider: ontap
    removal_policy: DESTROY
    ontap: {}

    #ExtraMounts:
    #  - dest: /apps
    #    src: fs-xxxxxxxx.efs.us-east-1.amazonaws.com:/
    #    type: nfs4
    #    options: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    #  - dest: /data
    #    src: fs-xxxxxxxx.efs.us-east-1.amazonaws.com:/
    #    type: nfs4
    #    options: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
