---
#====================================================================
# Test Rocky linux support
#
# Defaults and valid configuration options are in source/config_schema.py.
# Command line values override values in the config file.
#====================================================================

StackName: slurmrocky

slurm:
  InstanceConfig:
    UseSpot: true
    NodesPerInstanceType: 5
    BaseOsArchitecture:
      Rocky: {8: [x86_64, arm64]}
    Include:
      InstanceFamilies:
        - t3
        - t4g
      InstanceTypes: []

  # Use defaults from schema
  SlurmCtl: {}
  storage: {'zfs': {}}
