---
# Slurm cluster that uses Lustre for storing the Slurm configuration and tool files
# EFS should be adequate and more cost effective for most uses.
# You might consider Lustre for very large, dynamic clusters if they are putting a strain on EFS metadata.

StackName: slurmlustre

slurm:

  storage:
    provider: lustre
    lustre': {}

  # InstanceConfig:
  # Configure the instances used by the cluster
  # A partition will be created for each combination of Base OS, Architecture, and Spot
  InstanceConfig:
    UseSpot: true
    DefaultPartition: CentOS_7_x86_64_spot
    NodesPerInstanceType: 10
    BaseOsArchitecture:
      CentOS:
        7: [x86_64]
    Include:
      MaxSizeOnly: false
      InstanceFamilies:
        - t3
      InstanceTypes: []
    Exclude:
      InstanceFamilies: []
      InstanceTypes:
        - '.*\.metal'

  # Use defaults from schema
  SlurmCtl: {}
