---

- name: Show vars used in this playbook
  debug:
    msg: |
      cluster_name:                {{ cluster_name }}

- name: Remove modulefile configuration
  file:
    dest: /etc/profile.d/slurm_{{ cluster_name }}_modulefiles.sh
    state: absent

- name: Remove /opt/slurm/{{ cluster_name }} from /etc/fstab
  mount:
    path: /opt/slurm/{{ cluster_name }}
    backup: true
    fstype: nfs
    state: absent
