---
# Unmount SLURM file system

- name: Print vars
  debug:
    msg: |
      FileSystemDns:       {{FileSystemDns}}
      FileSystemMountPath: {{FileSystemMountPath}}
      FileSystemMountSrc:  {{FileSystemMountSrc}}
      FileSystemOptions:   {{FileSystemOptions}}
      FileSystemPort:      {{FileSystemPort}}
      FileSystemType:      {{FileSystemType}}

- name: Unmount SLURM file system
  mount:
    fstype: "{{FileSystemType}}"
    path: "{{FileSystemMountPath}}"
    state: absent

# For some reason the ansible module is leaving the file system mounted
- name: Unmount SLURM file system
  shell: |
    umount -f {{FileSystemMountPath}}

- name: Remove {{FileSystemMountPath}}
  file:
    state: absent
    path: "{{FileSystemMountPath}}"
