#!/bin/bash -ex
###############################################################################
##          Copyright (c) 2024 Exostellar Inc. All rights reserved.          ##
## Email:   support@exostellar.io                                            ##
###############################################################################

# Do not edit this file
# If you need to customize the VM image add your customizations to xspot-vm_custom_user_data.sh.

systemctl stop amazon-ssm-agent || true
systemctl disable amazon-ssm-agent || true

if ! [[ -d /opt/slurm ]]; then
    mkdir /opt/slurm
fi
if ! mountpoint /opt/slurm; then
    mount -t nfs -o defaults head_node.{{ cluster_name }}.pcluster:/opt/slurm /opt/slurm
fi

if ! [[ -d /opt/parallelcluster/shared ]]; then
    mkdir -p /opt/parallelcluster/shared
fi
if ! mountpoint /opt/parallelcluster/shared; then
    mount -t nfs -o defaults head_node.{{ cluster_name }}.pcluster:/opt/parallelcluster/shared /opt/parallelcluster/shared
fi

if ! [[ -d /opt/intel ]]; then
    mkdir -p /opt/intel
fi
if ! mountpoint /opt/intel; then
    mount -t nfs -o defaults head_node.{{ cluster_name }}.pcluster:/opt/intel /opt/intel
fi

if [[ -e /opt/slurm/config/users_groups.json ]]; then
    /opt/slurm/config/bin/create_users_groups.py -i /opt/slurm/config/users_groups.json
fi

if ! [[ -e /var/log/parallelcluster ]]; then
    mkdir -p /var/log/parallelcluster
    chmod 0777 /var/log/parallelcluster
fi

if [[ -e /opt/slurm/etc/exostellar/custom_xio_user_data.sh ]]; then
    /opt/slurm/etc/exostellar/custom_xio_user_data.sh
fi

if ! [[ -e /etc/profile.d/slurm.sh ]]; then
    cat <<EOF > /etc/profile.d/slurm.sh
PATH=$PATH:/opt/slurm/bin
MANPATH=$MANPATH:/opt/slurm/share/man

export PATH MANPATH
EOF
fi
source /etc/profile.d/slurm.sh

if ! [[ -e /etc/profile.d/slurm.csh ]]; then
    cat <<EOF > /etc/profile.d/slurm.csh
set path = ($path /opt/slurm/bin)
if ( ${?MANPATH} ) then
  setenv MANPATH ${MANPATH}:/opt/slurm/share/man
else
  setenv MANPATH :/opt/slurm/share/man
endif
EOF
fi

cat <<EOF > /etc/sysconfig/slurmd
SLURMD_OPTIONS='-N XSPOT_NODENAME'
EOF

hostnamectl set-hostname XSPOT_NODENAME

echo XSPOT_NODENAME > /var/run/nodename

scontrol update nodename=XSPOT_NODENAME nodeaddr=$(hostname -I)

systemctl start slurmd
