---
# Mount SLURM file system

- name: Print vars
  debug:
    msg: |
      file_system_dns:        {{ file_system_dns }}
      file_system_mount_path: {{ file_system_mount_path }}
      file_system_mount_src:  {{ file_system_mount_src }}
      file_system_options:    {{ file_system_options }}
      file_system_port:       {{ file_system_port }}
      file_system_type:       {{ file_system_type }}
      extra_mounts:           {{ extra_mounts }}

- name: Install nfs-utils
  yum:
    state: present
    name:
      - nfs-utils

- name: Create {{ file_system_mount_path }}
  file:
    path: "{{ file_system_mount_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Wait for file system dns to exist
  wait_for:
    host: "{{ file_system_dns }}"
    port: "{{ file_system_port }}"
    timeout: 1800 # 30 minutes

- name: Mount SLURM file system
  mount:
    backup: yes
    fstype: "{{ file_system_type }}"
    opts: "{{ file_system_options }}"
    path: "{{ file_system_mount_path }}"
    src: "{{ file_system_mount_src }}"
    state: mounted
