---
# tasks file for ami_SlurmNode

- name: Install slurm_node yum packages
  yum:
    state: present
    name:
      - emacs
      - hwloc-libs
      - mailx
      - munge

- name: Install slurm_node python packages
  pip:
    executable: /usr/bin/pip3
    state: latest
    name:
      - boto3
      - botocore
      - requests
      - urllib3

- name: Create slurm user
  user:
    name: slurm
    local: yes
    system: yes
    uid: '{{SlurmUid}}'
    create_home: false

- name: Create /var/spool/slurmd
  file:
    path: /var/spool/slurmd
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: Create /var/log/munge
  file:
    path: /var/log/munge
    state: directory
    owner: munge
    group: munge
    mode: 0755

- name: Create {{SlurmLogsDir}}
  file:
    path: "{{SlurmLogsDir}}"
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: Create {{SlurmLogsDir}}/nodes
  file:
    path: "{{SlurmLogsDir}}/nodes"
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: Create /var/log/slurm
  file:
    path: /var/log/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: Create /etc/logrotate.d/slurmd
  template:
    dest: /etc/logrotate.d/slurmd
    src:   etc/logrotate.d/slurmd
    owner: root
    group: root
    mode: 0644

- name: Wait for {{SlurmConfigDir}}/munge.key
  wait_for:
    path: "{{SlurmConfigDir}}/munge.key"
    timeout: 1800 # 30 minutes

- name: Copy {{SlurmConfigDir}}/munge.key to /etc/munge/munge.key
  copy:
    dest: /etc/munge/munge.key
    remote_src: true
    src: "{{SlurmConfigDir}}/munge.key"
    owner: munge
    group: munge
    mode: 0400

- name: Update /etc/systemd/system/munged.service
  template:
    dest: /etc/systemd/system/munged.service
    src: ../../SlurmCtl/templates/etc/systemd/system/munged.service
    owner: root
    group: root
    mode: 0644

- name: Update /etc/systemd/system/slurmd.service
  template:
    dest: /etc/systemd/system/slurmd.service
    src:   etc/systemd/system/slurmd.service
    owner: root
    group: root
    mode: 0644

- name: Create /opt/slurm/config
  file:
    path: /opt/slurm/config
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Update /etc/systemd/system/spot_monitor.service
  template:
    dest: /etc/systemd/system/spot_monitor.service
    src:   etc/systemd/system/spot_monitor.service
    owner: root
    group: root
    mode: 0644

- name: Enable/start spot_monitor.service
  service:
    name: spot_monitor
    enabled: yes
    state: started

- name: Create/Update Users
  template:
    src: ../../SlurmCtl/templates/etc/cron.d/slurm_users_groups
    dest: /etc/cron.d/slurm_users_groups
    owner: root
    group: root
    mode: 0600
    force: yes
