---
# Tasks for ParallelClusterCreateUsersGroupsJsonDeconfigure

- name: Show vars used in this playbook
  debug:
    msg: |
      ClusterName:                {{ ClusterName }}

- name: Delete cron to refresh {{ SlurmConfigDir }}/users_groups.json every hour
  file:
    dest: /etc/cron.d/slurm_{{ ClusterName }}_update_users_groups_json
    state: absent

- name: Unmount /opt/slurm/{{ ClusterName }}
  shell: |
    set -ex

    # Handle case where cluster was already deleted so the mountpoint is hung
    if ! timeout 1s /opt/slurm/{{ ClusterName }}; then
        echo "Mount point is hung. Source has already been deleted."
        umount -lf /opt/slurm/{{ ClusterName }}
    fi
    if ! mountpoint /opt/slurm/{{ ClusterName }}; then
        echo "/opt/slurm/{{ ClusterName }} already unmounted."
        exit 0
    fi
    umount -lf /opt/slurm/{{ ClusterName }} || lsof /opt/slurm/{{ ClusterName }}
  register: umount_results

- name: Show umount results
  debug:
    msg: |
      umount_results: {{ umount_results }}

- name: Remove /opt/slurm/{{ ClusterName }} from /etc/fstab and ignore errors
  mount:
    path: /opt/slurm/{{ ClusterName }}
    backup: true
    fstype: nfs
    state: absent
  # For some reason umount is failing with device busy even though running out of /tmp.
  # Retry it again without ignoring errors.
  ignore_errors: true

- name: Remove /opt/slurm/{{ ClusterName }} from /etc/fstab
  mount:
    path: /opt/slurm/{{ ClusterName }}
    backup: true
    fstype: nfs
    state: absent
