---

- name: Show vars used in this playbook
  debug:
    msg: |
      cluster_name:                   {{ cluster_name }}
      distribution:                   {{ distribution }}
      parallel_cluster_munge_version: {{ parallel_cluster_munge_version }}
      region:                         {{ region }}
      slurm_base_dir:                 {{ slurm_base_dir }}
      slurm_config_dir:               {{ slurm_config_dir }}
      slurm_uid:                      {{ slurm_uid }}

- name: Add /opt/slurm/{{ cluster_name }} to /etc/fstab
  mount:
    path: /opt/slurm/{{ cluster_name }}
    src: "head_node.{{ cluster_name }}.pcluster:/opt/slurm"
    fstype: nfs
    backup: true
    state: present # Should already be mounted

- name: Install epel from amazon-linux-extras
  when: ansible_facts['distribution'] == 'Amazon'
  shell:
    cmd: |
      set -ex
      amazon-linux-extras install -y epel
    creates: /etc/yum.repos.d/epel.repo

- name: Install epel
  when: ansible_facts['distribution'] == 'CentOS'
  yum:
    state: present
    name:
      - epel-release

- name: Install slurm_submitter packages
  yum:
    state: present
    name:
      - environment-modules
      - python3
      - wget
      - xz

- name: Remove yum munge package
  yum:
    state: absent
    name:
      - munge

- name: Create munge user
  user:
    name: munge
    system: yes
    state: present
    create_home: no


- name: Get current munge version
  register: munged_version_output
  shell: |
    if ! [ -e /usr/sbin/munged ]; then
        echo "NONE"
        exit 0
    fi
    /usr/sbin/munged -V | awk '{print $1}'

- set_fact:
    act_munged_version: "{{ munged_version_output.stdout }}"
    exp_munged_version: "munge-{{ parallel_cluster_munge_version }}"

- name: Show munged_version
  debug:
    msg: |
      act_munged_version: "{{ act_munged_version }}"
      exp_munged_version: "{{ exp_munged_version }}"

- name: Build munge version used by ParallelCluster ({{ parallel_cluster_munge_version }})
  when: act_munged_version != exp_munged_version
  shell: |
    set -ex

    cd /usr/local/src
    mkdir -p munge
    cd munge
    rm -f munge-{{ parallel_cluster_munge_version }}.tar.xz
    rm -f munge-{{ parallel_cluster_munge_version }}.tar
    rm -rf munge-{{ parallel_cluster_munge_version }}
    wget https://github.com/dun/munge/releases/download/munge-{{ parallel_cluster_munge_version }}/munge-{{ parallel_cluster_munge_version }}.tar.xz
    xz -d munge-{{ parallel_cluster_munge_version }}.tar.xz
    tar -xf munge-{{ parallel_cluster_munge_version }}.tar
    rm -f munge-{{ parallel_cluster_munge_version }}.tar
    cd munge-{{ parallel_cluster_munge_version }}
    ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 &> configure.log
    make
    make install &> make_install.log
  register: build_munge

- name: Create /var/log/munge
  file:
    path: /var/log/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Create /etc/munge with correct permissions
  file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Copy {{ slurm_config_dir }}/munge.key to /etc/munge/munge.key
  copy:
    dest: /etc/munge/munge.key
    src: "{{ slurm_config_dir }}/munge.key"
    remote_src: true
    force: true   # Has to be true or won't be copied when they are different.
    backup: true
    owner: munge
    group: munge
    mode: 0400
  register: munge_key

- name: Start munge
  when: build_munge.changed or munge_key.changed
  service:
    name: munge
    enabled: yes
    state: restarted

- name: Create slurm user
  user:
    name: slurm
    system: yes
    state: present
    create_home: no
    uid: "{{ slurm_uid }}"

- name: Configure modules
  template:
    dest: /etc/profile.d/slurm_{{ cluster_name }}_modulefiles.sh
    src:   etc/profile.d/slurm_modulefiles.sh
    owner: root
    group: root
    mode: 0644
    force: yes
