---
# Mount extra file systems

- name: Print vars
  debug:
    msg: |
      extra_mounts: {{ extra_mounts }}

- name: Install nfs-utils
  yum:
    state: present
    name:
      - nfs-utils

- name: Mount extra_mounts
  when: extra_mounts|length > 0
  loop: "{{ extra_mounts }}"
  mount:
    backup: yes
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    path: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: mounted
